### ISSUE TITLE
Bug 003: Major Collision Issues

### ISSUE THREAD

**Issue by PhobosPerdition** [MorganMcLaren/HeiBai_Game#2]
Somehow the Colliders for the buckets and the kill platforms have had their range extended. No amount of tinkering with the size of the colliders is resolving the issue.

**Comment by LuciferPatronGod** [comment]
Bug Description: 
Upon loading in prefabs for the Kill Platform and Paint Bucket in level creation, collision boxes are incorrect (too large) and cannot be fixed. 

Version
HeiBai v0.0.6

To Reproduce
Steps to reproduce the behavior:
1. Start new level scene.
2. Import aproipriate prefabs, including Kill Platform and Paint Bucket
3. Collision radius is massive and unfixable. 

Expected behavior
Prefab assets "Kill Platform" and "Paint Bucket" should import with out issue, and have in the past. 

Desktop System (please complete the following information):
- OS: Windows 10

Additional context
This issue is in level design, not in direct play testing, though does effect game play experience.

**Comment by MorganMcLaren** [comment]
Thanks to Daniel we found a stray collider hiding in one of the player children it has now been fixed.
